### ISSUE TITLE
qemu git 2.3.93 can't start your image

### ISSUE THREAD

**Issue by LowLevelMahn** [danisla/dockerfiles#1]
i try to run your NetBSD image with qemu (some later git version) using the given commandline in your start-script :

im getting this error:

qemu-system-sparc64: -netdev user,id=mynet0,net=192.168.178.0/24,dhcpstart=192.168.178.9,hostfwd=tcp::22-:22: could not set up host forwarding rule 'tcp::22-:22'
qemu-system-sparc64: -netdev user,id=mynet0,net=192.168.178.0/24,dhcpstart=192.168.178.9,hostfwd=tcp::22-:22: Device 'user' could not be initialized

any idea how to solve this?

**Comment by danisla** [comment]
@LowLevelMahn Thanks for reporting this. The `-netdev` arg only exists in newer versions of qemu. When I initially committed the Dockerfile, it was based on someone else's base image, which had qemu v2.3.0, since then, the base image changed so if you try to build the docker image again, you wouldn't get the correct version of qemu with the `-netdev` option. Pulling from the docker registry would have worked for you because the versions and everything were saved from the time I initially built it. 

So to fix this I updated my [Dockerfile](https://github.com/danisla/dockerfiles/blob/885f8353659eea5ad89b86593152ada087fcd07d/netbsd-sparc64/Dockerfile) so that it's based on the debian:stretch image which has qemu-2.3.0. Building the docker image by hand now works again. I've also pushed an updated image to the [Docker Hub](https://hub.docker.com/r/danisla/netbsd-sparc64/).

Cheers!

**Comment by LowLevelMahn** [comment]
but im using 2.3.93 (more recent than your 2.3.0) - i give it a try 
tomorrow with current 2.4 release

Am 15.08.2015 um 17:34 schrieb danisla:

**Comment by danisla** [comment]
@LowLevelMahn, this repo is primarily just to share my docker build of qemu. How did you get qemu version 2.3.93? I don't see that on the qemu github releases or tags: https://github.com/qemu/qemu.

**Comment by LowLevelMahn** [comment]
my qemu git head build from 2-3 weeks ago shows that on --version

i usualy just build git head

im building qemu 2.4.x right now

Am 16.08.2015 um 01:36 schrieb danisla:

**Comment by LowLevelMahn** [comment]
got it - my local port 22 is in use - so it fails to configure the port 
forwarding

what qemu parameters did you use for installation, do also got these 
problems with finding the hda and cdrom - need to type in
by manualy

Am 16.08.2015 um 07:49 schrieb Dennis Luehring:

**Comment by danisla** [comment]
@LowLevelMahn, got it, makes sense on the port 22, again, this is meant to be run within a container, which has it's own isolated networking stack.

I used all default installation options during the NetBSD install, I haven't found a way to fix the issue with entering the boot drive manually.  If you find a way or have any new run options or netbsd installation changes, please let me know or submit a pull request.
